import React from "react";
import { Badge, Button, PageTitle, Table } from "../components/ui";
import { BRANCH_CODE_MAP } from "../constants/branches";
import { STAFF_LEVEL_POLICIES } from "../config/staffPolicies";
import { money } from "../utils/format";

export function EmployeeAdd({ employee, setEmployee, save, close }) {
  return <div className="bg-white rounded-2xl shadow-sm border border-slate-100 mb-4 p-5"><div className="flex justify-between mb-4"><h2 className="text-lg font-bold">Add New Employee</h2><Button variant="outline" onClick={close}>Close</Button></div><div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-4 gap-3"><input placeholder="Full Name" value={employee.fullName} onChange={(e) => setEmployee({ ...employee, fullName: e.target.value })} className="px-4 py-2 border rounded-xl" /><input placeholder="Designation" value={employee.designation} onChange={(e) => setEmployee({ ...employee, designation: e.target.value })} className="px-4 py-2 border rounded-xl" /><input placeholder="Department" value={employee.department} onChange={(e) => setEmployee({ ...employee, department: e.target.value })} className="px-4 py-2 border rounded-xl" /><select value={employee.level} onChange={(e) => setEmployee({ ...employee, level: e.target.value })} className="px-4 py-2 border rounded-xl">{Object.keys(STAFF_LEVEL_POLICIES).map((x) => <option key={x}>{x}</option>)}</select><select value={employee.branch} onChange={(e) => setEmployee({ ...employee, branch: e.target.value })} className="px-4 py-2 border rounded-xl">{Object.keys(BRANCH_CODE_MAP).map((x) => <option key={x}>{x}</option>)}</select><input type="number" placeholder="Salary" value={employee.salary} onChange={(e) => setEmployee({ ...employee, salary: e.target.value })} className="px-4 py-2 border rounded-xl" /><input placeholder="Phone / WhatsApp" value={employee.phone} onChange={(e) => setEmployee({ ...employee, phone: e.target.value })} className="px-4 py-2 border rounded-xl" /><input placeholder="CNIC" value={employee.cnic || ""} onChange={(e) => setEmployee({ ...employee, cnic: e.target.value })} className="px-4 py-2 border rounded-xl" /><input placeholder="Father CNIC" value={employee.fathersCnic || ""} onChange={(e) => setEmployee({ ...employee, fathersCnic: e.target.value })} className="px-4 py-2 border rounded-xl" /></div><div className="mt-4"><Button onClick={save}>Save Employee</Button></div></div>;
}

export function EmployeeEdit({ employee, setEmployee, save, close }) {
  return <div className="bg-white rounded-2xl shadow-sm border border-slate-100 mb-4 p-5"><div className="flex justify-between mb-4"><h2 className="text-lg font-bold">Edit Employee</h2><Button variant="outline" onClick={close}>Close</Button></div><div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-4 gap-3"><input value={employee.name} onChange={(e) => setEmployee({ ...employee, name: e.target.value })} className="px-4 py-2 border rounded-xl" /><input value={employee.dept} onChange={(e) => setEmployee({ ...employee, dept: e.target.value })} className="px-4 py-2 border rounded-xl" /><select value={employee.level} onChange={(e) => setEmployee({ ...employee, level: e.target.value })} className="px-4 py-2 border rounded-xl">{Object.keys(STAFF_LEVEL_POLICIES).map((x) => <option key={x}>{x}</option>)}</select><input type="number" value={employee.salary} onChange={(e) => setEmployee({ ...employee, salary: e.target.value })} className="px-4 py-2 border rounded-xl" /></div><div className="mt-4 flex gap-2"><Button onClick={save}>Save Changes</Button><Button variant="outline" onClick={close}>Cancel</Button></div></div>;
}

export default function Employees({ query, setQuery, branch, setBranch, showEmployeeForm, setShowEmployeeForm, newEmployee, setNewEmployee, saveEmployee, editingEmployee, setEditingEmployee, updateEmployee, loadingEmployees, filteredEmployees, updateEmployeeStatus }) {
  return <div><PageTitle title="Employee Master" subtitle="Add, edit and mark staff inactive." action={<Button className="rounded-2xl" onClick={() => setShowEmployeeForm(true)}>+ New Employee</Button>} /><div className="flex flex-col md:flex-row gap-3 mb-4"><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search employee..." className="flex-1 px-4 py-2.5 rounded-2xl border border-slate-200" /><select value={branch} onChange={(e) => setBranch(e.target.value)} className="px-4 py-2.5 rounded-2xl border border-slate-200"><option>All</option>{Object.keys(BRANCH_CODE_MAP).map((b) => <option key={b}>{b}</option>)}</select></div>{showEmployeeForm && <EmployeeAdd employee={newEmployee} setEmployee={setNewEmployee} save={saveEmployee} close={() => setShowEmployeeForm(false)} />}{editingEmployee && <EmployeeEdit employee={editingEmployee} setEmployee={setEditingEmployee} save={updateEmployee} close={() => setEditingEmployee(null)} />}{loadingEmployees && <p>Loading employees...</p>}<Table headers={["ID", "Name", "Level", "Branch", "Department", "Salary", "Status", "Action"]} rows={filteredEmployees} renderRow={(e) => <tr key={e.id}><td className="px-4 py-3 font-medium">{e.id}</td><td className="px-4 py-3">{e.name}</td><td className="px-4 py-3">{e.level}</td><td className="px-4 py-3">{e.branch}</td><td className="px-4 py-3">{e.dept}</td><td className="px-4 py-3">{money(e.salary)}</td><td className="px-4 py-3"><Badge tone={e.status === "Active" ? "green" : "yellow"}>{e.status}</Badge></td><td className="px-4 py-3 flex gap-2"><Button variant="outline" onClick={() => setEditingEmployee(e)}>Edit</Button>{e.status === "Active" && <Button variant="outline" onClick={() => updateEmployeeStatus(e.id, "Inactive")}>Inactive</Button>}</td></tr>} /></div>;
}
