import React from "react";
import { Badge, Button, Card, CardContent, PageTitle, Table } from "../components/ui.js";
import { money } from "../utils/format.js";
import { downloadTemplate } from "../utils/downloads.js";

export default function Imports({ selectedFile, setSelectedFile, preview, importing, message, error, onPreview, onImport }) {
  const invalidCount = preview.filter((row) => !row.valid).length;
  return <div><PageTitle title="Import Center" subtitle="Download Excel templates, upload employee details, preview errors and confirm import." /><Card className="rounded-2xl border border-slate-100 shadow-sm mb-6"><CardContent className="p-6"><h2 className="text-lg font-bold mb-3">Download Templates</h2><div className="grid grid-cols-1 md:grid-cols-5 gap-3">{["employees", "attendance", "salary_adjustments", "loans", "leaves"].map((type) => <Button key={type} variant="outline" className="rounded-2xl" onClick={() => downloadTemplate(type)}>{type.replaceAll("_", " ")}</Button>)}</div></CardContent></Card><Card className="rounded-2xl border border-slate-100 shadow-sm mb-6"><CardContent className="p-6"><h2 className="text-lg font-bold mb-3">Upload Employee File</h2><input type="file" accept=".csv,.xls,.xlsx" onChange={(e) => setSelectedFile(e.target.files?.[0] || null)} className="block w-full text-sm mb-3" />{selectedFile && <p className="text-sm text-slate-600 mb-3">Selected: <b>{selectedFile.name}</b></p>}<div className="flex gap-3"><Button onClick={onPreview} className="rounded-2xl">Preview File</Button><Button onClick={onImport} disabled={importing || !preview.length || invalidCount > 0} className="rounded-2xl">{importing ? "Importing..." : "Confirm Import"}</Button></div>{message && <div className="mt-4 p-3 rounded-xl bg-blue-50 text-blue-700">{message}</div>}{error && <div className="mt-4 p-3 rounded-xl bg-red-50 text-red-700">{error}</div>}</CardContent></Card>{preview.length > 0 && <Table headers={["Row", "Employee ID", "Name", "Branch", "Level", "Salary", "Status"]} rows={preview} renderRow={(r) => <tr key={r.rowNumber}><td className="px-4 py-3">{r.rowNumber}</td><td className="px-4 py-3">{r.employee_code || "Auto"}</td><td className="px-4 py-3">{r.name}</td><td className="px-4 py-3">{r.branch}</td><td className="px-4 py-3">{r.level}</td><td className="px-4 py-3">{money(r.salary)}</td><td className="px-4 py-3"><Badge tone={!r.valid ? "red" : r.missingRequiredDetails?.length ? "yellow" : "green"}>{!r.valid ? r.errors.join(", ") : r.missingRequiredDetails?.length ? `Ready - complete later: ${r.missingRequiredDetails.join(", ")}` : "Ready"}</Badge></td></tr>} />}</div>;
}
