export const STAFF_LEVEL_POLICIES = {
  Management: {
    label: "Management",
    defaultShiftStart: "00:00",
    defaultShiftEnd: "00:00",
    requiredHours: 9,
    fridayHours: 6.5,
    breakMinutes: 60,
    graceMinutes: 0,
    halfDayLateMinutes: 0,
    halfDayEarlyOutMinutes: 0,
    latePenaltyCount: 3,
    latePenaltyDays: 0,
    overtimeEligible: false,
    overtimeAfterHours: 0,
    overtimeNeedsApproval: true,
    adjustShortHoursAgainstOT: false,
    // Working days notice required
    noticeDays: 78,
    weeklyOffDay: 0, // 0 = Sunday
    halfDayMinHours: 5,
    absentMinHours: 5,
  },
  "Floor Management": {
    label: "Floor Management",
    defaultShiftStart: "11:00",
    defaultShiftEnd: "21:30",
    requiredHours: 10.5,
    fridayHours: 9,
    breakMinutes: 45,
    graceMinutes: 15,
    halfDayLateMinutes: 90,
    halfDayEarlyOutMinutes: 90,
    latePenaltyCount: 3,
    latePenaltyDays: 1,
    overtimeEligible: false,
    overtimeAfterHours: 0,
    overtimeNeedsApproval: true,
    adjustShortHoursAgainstOT: true,
    noticeDays: 26,
    weeklyOffDay: -1, // rotating
    halfDayMinHours: 6,
    absentMinHours: 6,
  },
  "Non-Management": {
    label: "Non-Management",
    defaultShiftStart: "11:00",
    defaultShiftEnd: "21:30",
    requiredHours: 10.5,
    fridayHours: 9,
    breakMinutes: 45,
    graceMinutes: 15,
    halfDayLateMinutes: 90,
    halfDayEarlyOutMinutes: 90,
    latePenaltyCount: 3,
    latePenaltyDays: 1,
    overtimeEligible: true,
    overtimeAfterHours: 10.5,
    overtimeNeedsApproval: true,
    adjustShortHoursAgainstOT: true,
    noticeDays: 13,
    weeklyOffDay: -1, // rotating
    halfDayMinHours: 6,
    absentMinHours: 6,
  },
};

export const LOAN_POLICY = {
  minimumServiceYears: 2,
  maximumSalaryPercent: 90,
  maximumRepaymentMonths: 6,
  cooldownAfterRepaymentMonths: 12,
  requiresTwoGuarantors: true,
  requiresSurety: true,
};

export const LEAVE_QUOTA = {
  Management: 24,
  "Floor Management": 14,
  "Non-Management": 14,
};
