export const STAFF_LEVEL_POLICIES = {
  Management: {
    label: "Management",
    defaultShiftStart: "00:00",
    defaultShiftEnd: "00:00",
    requiredHours: 9,
    breakMinutes: 60,
    graceMinutes: 0,
    halfDayLateMinutes: 0,
    halfDayEarlyOutMinutes: 0,
    latePenaltyCount: 3,
    latePenaltyDays: 0,
    overtimeEligible: false,
    overtimeAfterHours: 0,
    overtimeNeedsApproval: true,
    adjustShortHoursAgainstOT: false,
    noticeDays: 90,
  },
  "Floor Management": {
    label: "Floor Management",
    defaultShiftStart: "11:00",
    defaultShiftEnd: "21:30",
    requiredHours: 10.5,
    breakMinutes: 45,
    graceMinutes: 15,
    halfDayLateMinutes: 90,
    halfDayEarlyOutMinutes: 90,
    latePenaltyCount: 3,
    latePenaltyDays: 1,
    overtimeEligible: false,
    overtimeAfterHours: 0,
    overtimeNeedsApproval: true,
    adjustShortHoursAgainstOT: true,
    noticeDays: 45,
  },
  "Non-Management": {
    label: "Non-Management",
    defaultShiftStart: "11:00",
    defaultShiftEnd: "21:30",
    requiredHours: 10.5,
    breakMinutes: 45,
    graceMinutes: 15,
    halfDayLateMinutes: 90,
    halfDayEarlyOutMinutes: 90,
    latePenaltyCount: 3,
    latePenaltyDays: 1,
    overtimeEligible: true,
    overtimeAfterHours: 10.5,
    overtimeNeedsApproval: true,
    adjustShortHoursAgainstOT: true,
    noticeDays: 15,
  },
};

export const LOAN_POLICY = {
  minimumServiceYears: 2,
  maximumSalaryPercent: 90,
  maximumRepaymentMonths: 6,
  cooldownAfterRepaymentMonths: 12,
  requiresTwoGuarantors: true,
  requiresSurety: true,
};
